### ISSUE TITLE
Poor framerate with Morrowind on Steam Deck

### ISSUE THREAD

**Issue by nokiomanz** [luxtorpeda-dev/packages#840] opened 2023-02-02 18:12 UTC
### Game

Morrowind

### Engine

OpenMW

### Linux Distribution

Steam Deck

### Luxtorpeda Version

v61

### Bug description

Playing the game with default settings give me between 30-40 FPS. I though it was normal.
But today on discord someone said that he has the same 30-40 fps but that under Flatpak version of OpenMW he his getting 200+fps.

I was told to open an issue here to investigate is case there is something that needs adjusting

### Steps To Reproduce

1. Install Luxtorpeda v61 using protonup-qt
2. Install Morrowind
3. Change Morrowind compatibility to use luxtorpeda
5. Start the game
6. Select first option to start openmw
7. Loading my save file that is just outside the house after the character creation at the beginning of the game

### Expected Behavior

If both Luxtorpeda and Flatpak use the same openMW engine on the steam deck. Should they not both get the same fps?

**Comment by d10sfan** [comment] 2023-02-03 20:19
@nokiomanz There should be a settings.cfg file in ~/.config/openmw, can you upload it here, so can see if there's anything interesting there? AS well, please send the launcher.cfg and openmw.log from the last attempt.

**Comment by nokiomanz** [comment] 2023-02-03 21:12
Will these do ?
[Archive.zip](https://github.com/luxtorpeda-dev/packages/files/10582840/Archive.zip)

**Comment by d10sfan** [comment] 2023-02-04 15:25
@nokiomanz Thanks, can you also send the /home/deck/.config/openmw/settings.cfg file?

**Comment by Tintin-Asterix** [comment] 2023-02-04 18:50
Same issue, lots of people are having this issue. Something I saw about GUI calls:

> The only thing I could tell, and you can check this too is see when you activate the profiler (F3) I forget if you press it twice or 3 times to get the graph. Check what your Gui values are. My draw was normal, but my Gui calls were getting close to 20. I tried to reinstall with Luxtorpeda but to no avail. Installing directly from Discover was the only thing that worked and now my Gui calls are between 0.1 to 0.4 instead of 20.0. I have a feeling there is something wrong with the way Luxtorpeda is delivering the openMW files in a recent update, but I don't know enough about it to tell.

Checked on my Deck and I also have GUI calls at about 20. Whether this is causing the slowdown or just a product of it, I do not know.

**Comment by nokiomanz** [comment] 2023-02-04 19:11
@d10sfan Unless I did a mistake. In the zip file you should find 3 files. 
All were under the specified folder /home/deck/.config/openmw/

It contains 
- settings.cfg
- openmw.log
- openmw.cfg

**Comment by d10sfan** [comment] 2023-02-05 16:07
Ah yes, you're right, sorry got confused there for a bit. Does the openmw-latest one do the same thing?

It might be the version of or how the dependent libraries were built, curious if openmw-latest does the same thing with the draw calls.

**Comment by nokiomanz** [comment] 2023-02-05 16:27
I just started with latest. It is the same 30-40 fps. I cannot say about that draw calls things though as I am not sure how to check that correctly. So maybe @Tintin-Asterix can comment on this. But since I seem to have the same behavior I woulld guess that it's the same there as well.

**Comment by d10sfan** [comment] 2023-02-05 17:23
Ok, I'll take a look when I have a chance, thanks

**Comment by phildogtheman** [comment] 2023-02-05 21:28
I have this exact issue, I was running openmw through luxtorpeda with fps at 60+
I was about 80 hours into my game when I pressed the steam button to change some controller confit - the GUI flidded out and then the whole deck crashed. Ever since then performance has tanked and I’m getting similar poor performance to what is described here. I also can get great performance through the discover app and manually installing openmw.

I noticed the GUI calls were now extremely high through luxtorpeda and Can’t help but think that some conflict has happened with the steam UI. I’ve tried everything, even reimaging the steam deck and the problem remains. Going to wait for a fix before I carry on as want the shaders that luxtorpeda offers.

**Comment by d10sfan** [comment] 2023-02-05 22:35
Can you all try with the steam overlay disabled? Wondering if something there could be interfering

**Comment by nokiomanz** [comment] 2023-02-05 22:43
I opened the setting and unchecked the steam overlay for the game.
Loaded my save, same result. no change.

**Comment by phildogtheman** [comment] 2023-02-05 22:43
Yeah same result for me too

**Comment by nokiomanz** [comment] 2023-02-05 22:48
I found a few reddit post that are recent and indicate the same behavior.
Not much more info in those. But listing for reference in case that is at all usefull.

https://www.reddit.com/r/SteamDeck/comments/10kvbty/only_getting_around_40fps_on_morrowind_when_the/
https://www.reddit.com/r/SteamDeck/comments/10r3wt8/openmw_suddenly_horrid_fps/

**Comment by d10sfan** [comment] 2023-02-12 15:27
Thanks, I'll take a look when I can

**Comment by phildogtheman** [comment] 2023-02-16 13:08
had another blast trying to see if anyone had found a fix for this so I can get back to my game and came across another couple of posts if it helps.

https://www.reddit.com/r/OpenMW/comments/10kcqh0/openmw_047_on_steam_deck_low_fps_after_changing/
https://www.reddit.com/r/SteamDeck/comments/10kowv9/openmwluxtorpeda_issue/

Seems like this is an issue for everyone on steamdeck.

**Comment by d10sfan** [comment] 2023-02-16 13:42
I tried some changes that didn't appear to help, I am able to replicate it on the steam deck as well, it is odd, since I remember it working better like others have mentioned. I'll see what else I can find out.

**Comment by phildogtheman** [comment] 2023-02-16 15:22
Thanks mate, appreciate it as keen to carry on with my save. It’s weird, one second working so brilliantly I was impressed then next FPS nose dived

**Comment by d10sfan** [comment] 2023-03-15 15:14
It does not seem directly related to gamescope from a quick test I did on my system, was curious if that was an issue. I'll update once i may know more.

**Comment by ramonDexter** [comment] 2023-03-23 09:06
I can report the same issue. After a week of adjusting settings wil little to no result, I tried installing flatpak openmw. Performance is butter smooth with the flatpak, while the luxtorpeda one has drops under 30fps...

Also, could you please add option to download not the latest one? The stable 0.47.0 runs just fine, so it would be nice to have this option also available.

**Comment by d10sfan** [comment] 2023-03-23 10:20
@ramonDexter Not sure what you mean, the stable one (0.47.0) is the one called "openmw"

**Comment by CptCookies12** [comment] 2023-03-30 19:07
Also can report that this issue is still occurring on a fresh install of the game and Luxtorpeda v62 on Steam Deck. Regardless of if I use either stable (openmw) or the Latest build, the framerate's unreasonably slow at around the low 15-20 FPS range no matter what settings I use. Even running the game without any extra mods and the shaders on legacy still cause the framerate to be locked below 20. The Flatpak version doesn't have this issue at the moment.

At some point I could test on my desktop running Nobara to see if the issue still occurs outside of the Deck, but is it possible there's some dependency or something about how Luxtorpeda builds OpenMW that's different from the official releases? I remember seeing a comment somewhere that one of the devs behind OpenMW [has a script for compiling AppImages on the Discord server](https://old.reddit.com/r/OpenMW/comments/x4nwj9/how_to_get_the_latest_build_on_steam_deck/imwecqc/) that also don't suffer this same performance issue.

**Comment by d10sfan** [comment] 2023-03-30 19:21
It's odd because at least on my desktop, I don't see this issue. I did try some optimizations at one point but need to delve into their release ideas at some point.

This used to work better without any changes on my end from my understanding, so maybe a driver change of some sort messed with it. I have an old laptop with only an integrated gpu and I'm getting 300 fps on the same build. 

I haven't had a chance to delve deeply into that yet, but hopefully soon, and also if anyone else has any ideas feel free to jump in.

**Comment by Patryz** [comment] 2023-04-17 08:58
Confirming issue is still present as of today, luxtorpeda v62. Any settings to tdp or gpu power is completely ineffective

**Comment by d10sfan** [comment] 2023-04-17 13:29
Still don't have anything new on this issue. I've tried a few  things to see, and even the newer openmw-latest has the same problem.

On my desktop and a laptop that's much less powered than the deck I get much better framerate, so still not sure what the issue is. 

I'll update once I have something more on this.

**Comment by Tintin-Asterix** [comment] 2023-06-17 15:38
This issue is now present on all versions of OpenMW on Deck it seems, Luxtorpeda, Flatpak, Appimage, etc. Something changed in either the SteamOS updates or whatever and now all versions have this exact heavy frame lag bug. I did fresh installs of all OpenMW versions with clean config files. 

I suspected it probably wasn't anything to do with Luxtorpeda originally but now I think I was right. OpenMW itself is busted.

Guess I won't be playing Morrowind on the Deck for a while. Shame.

**Comment by Zebrazilla** [comment] 2023-07-10 05:45
Just chiming in that this is still an issue on v65.1.0

**Comment by d10sfan** [comment] 2023-07-23 04:41
I've updated OpenMW to 0.48.0 and this is now using the binaries provided by the upstream repo, instead of building it here.

The performance on the steam deck is a bit better but still seems worse than it should be. Interestingly, I noticed that running the same exact binaries outside of steam works fine performance wise (100+ fps), but inside seem (either using luxtorpeda, or just creating a non-steam shortcut), the fps drops to 40-50 fps.

So it looks like the problem is with something on steam itself, and not luxtorpeda.

I've created a ticket with SteamOS to see what Valve thinks about this, it may be some sort of issue with OpenMW itself, but seems likely sometime may be wrong with Steam somehow. https://github.com/ValveSoftware/SteamOS/issues/1102

As of this, I'll close this since it isn't our bug, I'll try and update it if I find out more information. Please feel free to comment if you have any questions/issues.

**Closed by d10sfan** 2023-07-23 04:41 UTC
Labels: engine bug

**Comment by d10sfan** [comment] 2023-07-23 13:41
I also created an issue with openmw: https://gitlab.com/OpenMW/openmw/-/issues/7498

**Comment by padawin** [comment] 2023-07-26 07:39
Also, it works fine when Morrowind is installed as a non Steam product (e.g. via GOG/Lutris), and OpenMW configured against it. That way, the game runs smoothly. But as soon as I use the Steam version, it is unplayable. 
If it can help anyone, once back at home I can provide details of my installation.

**Comment by d10sfan** [comment] 2023-07-26 13:26
Is that referring to running it in desktop mode outside of steam? If so, that tracks with what I'm seeing, where running inside steam is dropping the framerate for some reason.

**Comment by padawin** [comment] 2023-07-27 08:14
No, I run it in handheld mode inside Steam.

**Comment by d10sfan** [comment] 2023-07-27 13:14
Not sure why that would be unless there's something in the morrowind assets themselves different steam vs gog, but hopefully one of those issues will help figure out the issue.

**Comment by vladzbuker** [comment] 2023-07-30 12:05
Confirming this issue.
Launching OpenMW(GOG version) in Gaming Mode results in 14 FPS, but launching in from Decstop Mode results in 100+ FPS. 
Weird bug =//

**Comment by PPJMM** [comment] 2023-08-04 18:22
> Confirming this issue. Launching OpenMW(GOG version) in Gaming Mode results in 14 FPS, but launching in from Decstop Mode results in 100+ FPS. Weird bug =//

Oh, wait, just to clarify: you are launching the GOG version from Steam, not OpenMW from GOG Galaxy, resulting in the heavy frame drop, right? If it's the latter, that might actually make it an issue of OpenMW, compared to Steam!

**Comment by d10sfan** [comment] 2023-09-29 20:42
Thanks to a comment here (https://gitlab.com/OpenMW/openmw/-/issues/7498), I've pushed a workaround and now openmw should run at a good framerate in luxtorpeda on the deck. It looks like either openmw or the deck is causing some issue there, the low fps was happening with or without lux.

**Comment by d10sfan** [comment] 2025-08-04 14:08
No worries, yes this is for using luxtorpeda-dev for a steam install, not for a non-steam install. You can try some of the things that worked here like `SteamDeck="" %command%`, but if you need support you should go to openmw or the flatpak repo.
