### ISSUE TITLE
Luxtorpeda enabled games fail to launch

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#386] opened 2021-08-03 11:10 UTC
**Luxtorpeda enabled games fail to launch on Ubuntu Mate 20.04**

On a fresh Ubuntu Mate 20.04, fresh Steam installation, games fail to launch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Luxtorpeda

https://github.com/luxtorpeda-dev/luxtorpeda#installation-using-tarball

2. Enable Luxtorpeda on Steam and specific games.
3. Install and launch the games.

**Expected behaviour**
Games to utilize Luxtorpeda and launch after Steam Play notice.

**Additional context**

- Entropy : Zero: https://gist.github.com/rea987/1040b4b43b2756eb568731addb3f4f3e
- Minerva: https://gist.github.com/rea987/8d47c8d66cc3a94a4fba7adbc8f0b17b
- Quake 3: Arena: https://gist.github.com/rea987/b8168b86022bf87b8b7fbd152c152575

`user_packages_file not found` line in all 3 logs is peculiar.

**Comment by d10sfan** [comment] 2021-08-03 13:05
Closing as duplicate of https://github.com/luxtorpeda-dev/luxtorpeda/issues/75

Please continue discussion there.

**Closed by d10sfan** 2021-08-03 13:05 UTC
Labels: engine bug

**Comment by d10sfan** [comment] 2021-08-03 13:07
Also user_packages_file not found is normal, that just means that the user override of packages.json is not there.
