### ISSUE TITLE
Half Life: Entropy Zero asks to locate a folder with a file that doesn't exist

### ISSUE THREAD

**Issue by DuendeInexistente** [luxtorpeda-dev/packages#723] opened 2022-08-26 17:09 UTC
### Game

Half Life: Entropy Zero

### Engine

Half Life SDK 2013 

### Linux Distribution

64 bits ubuntu 22

### Luxtorpeda Version

57

### Bug description

Trying to launch Entropy Zero through luxtorpeda, there's a prompt where I have to find the steam runtime folder and that it should have a file named ``scout-on-soldier-entry-point-v2``. This file doesn't exist anywhere in my .steam folder (I ran find) and pointing to ~/.steam/steam/ubuntu12_32/steam-runtime (or ubuntu12_64) fails.  Is there any requirement other than

### Steps To Reproduce

Try to run, point it to steam runtime folder

### Expected Behavior

the file existing at all

**Comment by d10sfan** [comment] 2022-08-26 17:57
Closing as duplicate of https://github.com/luxtorpeda-dev/packages/issues/722, as it relates to the same issue.

**Closed by d10sfan** 2022-08-26 17:57 UTC
Labels: engine bug
