### ISSUE TITLE
NAM - eduke32 not working

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#255] opened 2021-02-16 00:29 UTC
This is the first Luxtorpeda game that's had bugged like this for me. When the pick one of three options comes up, none of the choices work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install NAM
2. Set Luxtorpeda as the compatibility tool
3. Try to run NAM

**Expected behaviour**
edkue32 should start in a small window like Duke Nukem 3D or Shadow Warrior
. This is probably due to the eduke32 installing to the dosbox_windows folder instead of the ./steamapps/common/Nam/NAM directory

**Screenshots**
![Right](https://user-images.githubusercontent.com/79120763/108004501-0ac6b580-6fc4-11eb-9c08-967f759b3a25.png)
![Wrong](https://user-images.githubusercontent.com/79120763/108004511-10240000-6fc4-11eb-9747-c70b84f4b690.png)

**Additional context**
Good Luck, thanks for your hard work!

**Comment by d10sfan** [comment] 2021-02-16 15:38
Thanks for the ticket. I'll take a look at soon as I can, internet is currently out on my home network.

This was one that I don't own so thanks for testing and reporting. I'll comment once I have a fix or if I need some more information

**Comment by d10sfan** [comment] 2021-02-17 04:22
@Frenzied-Pop I think I've fixed it in this pull request: https://github.com/luxtorpeda-dev/packages/pull/256

If you try to launch the game again, it should automatically download the changes. Can you see if that fixes it?

**Comment by rea987** [comment] 2021-02-17 19:24
> run-nam.sh is still pointing to ./Nam/dosbox_windows/ and trying to execute eduke32 there. eduke32 is installed there by Luxtorpeda, but nam.grp, nam,con, etc are in ./Nam/NAM/ Also- I had so make a symbolic link "libvpx.so.1" when I ran the executable in the eduke32-2 package in ./Nam/NAM.

https://www.reddit.com/r/linux_gaming/comments/lk8wp9/redneck_rampage_commander_keen_nam_and_world_war/gnrlzuy/

**Comment by d10sfan** [comment] 2021-02-17 22:15
Thanks for the update, I'd need to game to proceed, cause that'll make it much clearer what the problem is. I'll see whenever it's on sale.

**Comment by d10sfan** [comment] 2021-02-17 22:36
Fixed in https://github.com/luxtorpeda-dev/packages/commit/947087d67d5c85c46acfbd46de53fce13bc36905

Looks like the issue was a combination of the scripts not pointing to the correct directory, and the scripts themselves didn't have the right permissions. It should work ok now.

**Closed by d10sfan** 2021-02-17 22:36 UTC
Labels: engine bug
