### ISSUE TITLE
Raze/Blood Doesn't Launch

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#361] opened 2021-05-14 17:00 UTC
**Describe the bug**
When launching Blood with the Raze engine nothing happens.

If Steam is launched from the terminal the following message can be seen:
```
Please select a game wad (or 0 to exit):
1. BLOOD: One Unit Whole Blood (BLOOD)
2. BLOOD: Cryptic Passage ()
Which one?
```

Then you can select one or two and the game will launch normally.

**Expected behaviour**
I think a good method for selecting the game would be to have four engines selectable, Raze/Blood and Raze/Cryptic Passage, nblood/Blood and nblood/Cryptic Passage.

Fresh Supply ([1010750](https://steamdb.info/app/1010750/config/)) has two launch options, and we can derive the desired game from that, but One Unit Whole Blood (https://steamdb.info/app/299030/config/) does not. It is currently not possible to select nblood/Cryptic Passage on One Unit Whole Blood for that reason, Raze/Cryptic Passage is selectable only because of the terminal menu.

**Comment by d10sfan** [comment] 2021-05-14 17:29
A GUI is supposed to come up in that case, I'm guessing possibly because of the windowing system you have it does not.

Do you have the correct commands to launch those games with Raze? 

For fresh supply, it's already setup to launch based on what launch option you pick, but I don't believe it's setup to automatically do it for raze.

For Whole Blood, we'd have to ask most likely. I don't own that game, so would need to know what the file paths and correct commands would be.

**Comment by JoshuaFern** [comment] 2021-05-14 18:42
All of the following commands are tested working:
One Unit/nblood/Blood: `./nblood -usecwd -nosetup`
One Unit/nblood/Cryptic Passage: `./nblood -usecwd -nosetup -ini CRYPTIC.INI`
One Unit/Raze/Blood: `./raze -gamegrp BLOOD.RFF`
One Unit/Raze/Cryptic Passage: `./raze -cryptic`

Launching Raze with these launch options also bypasses the game selection problem.

**Comment by d10sfan** [comment] 2021-05-14 20:35
@JoshuaFern 

Do you have the "Whole Blood" game? I do not own it, so would need the commands for that.

I do own One Unit, so can add that for raze. nblood is already setup.

**Comment by d10sfan** [comment] 2021-05-14 20:44
@JoshuaFern 

I'm getting this error trying cryptic with those commands: Initialization: CRYPTIC.INI does not exist

**Comment by JoshuaFern** [comment] 2021-05-14 23:24
You have Fresh Supply, I have both Fresh Supply and One Unit Whole Blood. Those commands are for One Unit Whole Blood.

**Comment by d10sfan** [comment] 2021-05-15 15:58
I've added the raze cryptic launch option in this: https://github.com/luxtorpeda-dev/packages/commit/c1ce6f620c6373632077db4566b33f64d37ca530

As well as made the Fresh Supply not prompt with the dialog.

**Comment by JoshuaFern** [comment] 2021-05-15 18:25
Fresh Supply/nblood/Blood: Tested working.
Fresh Supply/nblood/Cryptic Passage: Tested working.
Fresh Supply/Raze/Blood: Tested working.
Fresh Supply/Raze/Cryptic Passage: Tested working.

One Unit/nblood/Blood: Tested working.
One Unit/nblood/Cryptic Passage: Missing? Should be `./nblood -usecwd -nosetup -ini CRYPTIC.INI`
One Unit/Raze/Blood: Tested working.
One Unit/Raze/Cryptic Passage: Failed with error.
```
run: "./run-raze-nblood-cryptic-one-unit.sh" with args: [] ["-conf", "dosboxBlood.conf", "-noconsole", "-c", "exit"]
thread 'main' panicked at 'failed to execute process: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:225:13
```

This is originally a dosbox game, so it's launching with `-conf dosboxBlood.conf -noconsole -c "exit"`

**Comment by d10sfan** [comment] 2021-05-15 19:28
https://github.com/luxtorpeda-dev/packages/commit/ef53afdda46599ea98d0aff90158cb53e16dbb78
https://github.com/luxtorpeda-dev/packages/commit/970c86eccf9f29ae5b91d47aceb7f6d510553f42

Those commits should fix that issue.

**Comment by JoshuaFern** [comment] 2021-05-16 12:16
One Unit/nblood/Cryptic Passage: Tested working.
One Unit/Raze/Blood: No longer working `Initialization BLOOD.INI does not exist.`
One Unit/Raze/Cryptic Passage: Not working `Initialization CRYPTIC.INI does not exist.`

Any ideas what might cause this? The files are certainly there and it was working before.

**Comment by d10sfan** [comment] 2021-05-16 12:58
@JoshuaFern 

You'll see that for Fresh supply, I had to put the path directly for cryptic passage for raze:

LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./raze -con "addons/Cryptic Passage/CRYPTIC.INI" -gamegrp BLOOD.RFF -j "addons/Cryptic Passage"

For it to load, otherwise I got a similar error. If  you can provide similar commands that work for One Unit, then I can update the scripts for that.

**Comment by JoshuaFern** [comment] 2021-05-16 14:09
Right, that shouldn't be needed for One Unit Whole Blood because it's the DOS version of the game and it doesn't sort the Cryptic Passage addon into its own folder, rather all the game files are in ./ and these commands were working fine before.

I've been tinkering with this for hours, playing with various launch options - I still have no idea why it won't load the INI file.

However I stumbled upon a breakthrough. I started toying with the idea of trying to make a copy of BLOOD.INI to another folder and launch it there. So I copied it to ./ini/BLOOD.INI and I didn't realize it right away, but for some reason the both games work perfectly now with the same launch options I suggested.

I have so many questions but at least it works. I suggest copying (not moving) ./BLOOD.INI to ./ini/BLOOD.INI
Cryptic's INI doesn't need to be copied for some reason.

**Comment by d10sfan** [comment] 2021-05-17 01:10
@JoshuaFern Ok, this should be fixed in this: https://github.com/luxtorpeda-dev/packages/commit/9e5b8415c567ac41c1bc163b39be287850223035

Let me know how it goes.

**Comment by JoshuaFern** [comment] 2021-05-17 12:33
Alright, I deleted the ini modifications I had made and tested them again.

One Unit/Raze/Blood: Working, but showing the terminal menu again.
One Unit/Raze/Cryptic Passage: Working perfectly, no terminal menu.

run-raze-nblood-one-unit.sh should contain:
`LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./raze -gamegrp BLOOD.RFF`

**Comment by d10sfan** [comment] 2021-05-17 12:48
@JoshuaFern Try this: https://github.com/luxtorpeda-dev/packages/commit/dc2e1fc915e79dca59c967d517ca42c8e8222a3b

**Comment by JoshuaFern** [comment] 2021-05-17 14:21
I have no idea why, but both are again not working after this update. I think there's a serious bug with the engine itself, because none of this behavior makes any sense to me.

**Comment by d10sfan** [comment] 2021-05-17 14:53
@JoshuaFern Ok, can you create a pull request once you figure out the right commands for that game?

**Comment by JoshuaFern** [comment] 2021-05-18 00:20
I think the commands are correct, there's just something funky going on. I'm feeling frustrated so I'm going to take a break on this game.

**Comment by McMarius11** [comment] 2021-08-09 18:39
> @JoshuaFern
> 
> I'm getting this error trying cryptic with those commands: Initialization: CRYPTIC.INI does not exist
> 
> Looks like this: LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./raze -cryptic

i have the exact same problem, if i want to launch Fresh Supply or Cryptic Passage with Raze.

**Comment by d10sfan** [comment] 2021-08-09 18:45
@McMarius11 Renaming blood.ini to BLOOD.INI fixes only fresh supply? And raze works ok without this change?

Have you launched this in Windows before or proton?

**Comment by d10sfan** [comment] 2021-08-09 18:46
@McMarius11 Also which game steam id is it that you're launching?

**Comment by McMarius11** [comment] 2021-08-09 18:49
> @McMarius11 Renaming blood.ini to BLOOD.INI fixes only fresh supply? And raze works ok without this change?
> 
> Have you launched this in Windows before or proton?

app/1010750

yes, only for fresh supply. For the error to appear i had to install kdialog, im running Manjaro KDE.

no i can instantly reproduce the issue. i have not run it with something else only with luxtorpeda

**Comment by d10sfan** [comment] 2021-08-09 18:56
@McMarius11 You may need to install luxtorpeda-dev version 30 for the kdialog part (it'll fall back on zenity if you're using kde but kdialog is not installed).

Did you confirm a prompt for default engine choice? If so, that will survive the game uninstall. If you want to clear it, you can remove it in ~/.config/luxtorpeda/appid

**Comment by d10sfan** [comment] 2021-08-09 19:01
Interesting, I own the same game on steam and both games are working ok for me.

Can you check what you have in ~/.config/raze and provide the log?

Also, check the ini file, there may be something in there interfering with the steam version if you've run raze before for this game for another reason.

**Comment by JoshuaFern** [comment] 2021-08-09 19:01
I'm having the same problem, fresh install.

Fresh Supply(1010750)/Raze/Blood: Initialization: BLOOD.INI does not exist
Fresh Supply(1010750)/Raze/Cryptic: Initialization: addons/Cryptic Passage/CRYPTIC.INI does not exist
One Unit(299030)/Raze/Blood: Works.
One Unit(299030)/Raze/Cryptic: Starts Blood instead of Cryptic.

Also Fresh Supply(1010750) is again showing the terminal menu, from the first post in this thread:
 ```
Please select a game wad (or 0 to exit):
1. BLOOD: One Unit Whole Blood (BLOOD)
2. BLOOD: Cryptic Passage ()
Which one?
```

**Comment by McMarius11** [comment] 2021-08-09 19:04
> Interesting, I own the same game on steam and both games are working ok for me.
> 
> Can you check what you have in ~/.config/raze and provide the log?
> 
> Also, check the ini file, there may be something in there interfering with the steam version if you've run raze before for this game for another reason.
thanks i removed the config and reinstalled the game

i use the version 30 and if i remove kdialog and run flash blood with nblood everything works, if i want to use raze nothing will happen if i click on "not set as default" and the window closes itself. for the passage and fresh supply

**Comment by d10sfan** [comment] 2021-08-09 19:05
@JoshuaFern @McMarius11 

Does nblood work for you without any changes? As in is this issue isolated to raze?

I don't own one unit (299030) so I won't be able to help there unless someone could either gift me that game or can provide me with the correct command to run it.

For fresh supply, I do own it and I can't replicate the issue, even after a fresh install. 

What does your directory listing look like for Blood? I have a "blood.ini" and "BLOOD.RFF" files in the root, then addons/Cryptic Passage/CRYPTIC.INI

**Comment by d10sfan** [comment] 2021-08-09 19:07
@JoshuaFern I have a "sounds.rff", it looks like yours is complaining about not finding "SOUNDS.RFF". Does anything change for you if you copy the "sounds.rff" and name thecopy "SOUNDS.RFF"?

**Comment by McMarius11** [comment] 2021-08-09 19:17
> @JoshuaFern @McMarius11
> 
> Does nblood work for you without any changes? As in is this issue isolated to raze?
> 
> I don't own one unit (299030) so I won't be able to help there unless someone could either gift me that game or can provide me with the correct command to run it.
> 
> For fresh supply, I do own it and I can't replicate the issue, even after a fresh install.
> 
> What does your directory listing look like for Blood? I have a "blood.ini" and "BLOOD.RFF" files in the root, then addons/Cryptic Passage/CRYPTIC.INI

yes the the files are in the same paths here is the fix or bug

----beginning -everything clean-

fresh supply -> raze -> no -> crash
cryptic passage -> raze -> no -> crash

second run ( not cleaned )

fresh supply -> nblood -> no-> works
cryptic passage -> nblood -> no -> runs fresh supply

third run ( not cleaned )

fresh supply -> raze -> no-> works
cryptic passage -> raze -> no -> works

**Comment by JoshuaFern** [comment] 2021-08-09 19:18
Fresh Supply(1010750)/nBlood/Blood: Works
Fresh Supply(1010750)/nBlood/Cryptic: Skips launcher settings, goes into Blood instead of Cryptic.
One Unit(299030)/nBlood/Blood: Works.
One Unit(299030)/nBlood/Cryptic: Works.

Renaming "sounds.rff" to "SOUNDS.RFF", no effect. Same error message.

Full Directory trees:
Fresh Supply(1010750): https://gist.github.com/JoshuaFern/ed6f0c311bd9f60de64c582c6cbc5364
One Unit(299030): https://gist.github.com/JoshuaFern/807db7d2dfa78cd675be7a3ac4ba7864

**Comment by d10sfan** [comment] 2021-08-09 19:28
That kdialog prompt you're seeing is from raze itself. It seems to indicate it's having issues finding the right game to launch.

Do you all know where raze and nblood store their configuration? I found ~/.config/raze but it seems there must be some place else. I'm thinking that I have some stale configuration that is making my system work. Both nblood and raze work on my system.

Also when you do the uninstall, check if there are any files left over and try removing those. Then install the game again and try launching.

**Comment by McMarius11** [comment] 2021-08-09 19:32
> That kdialog prompt you're seeing is from raze itself. It seems to indicate it's having issues finding the right game to launch.
> 
> Do you all know where raze and nblood store their configuration? I found ~/.config/raze but it seems there must be some place else. I'm thinking that I have some stale configuration that is making my system work. Both nblood and raze work on my system.
> 
> Also when you do the uninstall, check if there are any files left over and try removing those. Then install the game again and try launching.

yeah with everything clean i meant i removed every file in the blood folder, yeah i removed everything in ~/.config/raze and the error is the same. only when i run nblood and then raze it works :D

**Comment by d10sfan** [comment] 2021-08-09 19:35
@McMarius11 Interesting, that says that possibly something that nblood is doing to the files, either creating one, or changing one, is making raze work as well. Can you see if you can isolate the files changed/edited to narrow down what may be causing this?

**Comment by JoshuaFern** [comment] 2021-08-09 19:37
I did a full filesystem search, the only two configuration locations is `~/.config/raze` and `nblood.cfg` which resides in the game folder.

I deleted the entire `~/.config/raze` and I still get the same error message for Fresh Supply(1010750)/Raze/Blood: Initialization: BLOOD.INI does not exist but oddly Fresh Supply(1010750)/Raze/Cryptic now works properly.

**Comment by d10sfan** [comment] 2021-08-09 19:55
I just replicated the raze popup coming up (showing it can't find the right file to launch). That occured by a fresh install and deleting the ~/.config/raze folder. Then the next time I launched the game with raze it loaded correctly. 

Does that sound about right for what you all are seeing as well? It may be that kdialog or something is needed for raze to even show that dialog, but it seems like something that raze is doing in the first launch is getting it over some issue.

**Comment by JoshuaFern** [comment] 2021-08-09 19:57
I'm not using kdialog at all on my end, but I have Steam running from a terminal emulator so I can select the game when prompted. That general behavior sounds about right though.

**Comment by JoshuaFern** [comment] 2021-08-09 20:04
Idea: What if we set the $HOME for these games to somewhere Luxtorpeda owns so we can perform automatic configuration changes without messing with the user's files?

**Comment by d10sfan** [comment] 2021-08-09 20:34
@JoshuaFern There's a  -config raze.ini command line argument that can be used to set it. I'm thinking we copy the built raze.ini into the package and then put it in the game directory. Hopefully that'll make it work the first time.

**Comment by McMarius11** [comment] 2021-08-09 20:35
> I just replicated the raze popup coming up (showing it can't find the right file to launch). That occured by a fresh install and deleting the ~/.config/raze folder. Then the next time I launched the game with raze it loaded correctly.
> 
> Does that sound about right for what you all are seeing as well? It may be that kdialog or something is needed for raze to even show that dialog, but it seems like something that raze is doing in the first launch is getting it over some issue.

with raze it did not appear not even on the 3 try.

here are the files that are needed for it to run

nblood
nblood.cfg
nblood.log (maybe not)
nblood.pk3
run-nblood-cryptic-one-unit.sh
run-nblood.sh
settings.cfg
texturecache
texturecache.index

**Comment by d10sfan** [comment] 2021-08-09 21:28
I pushed up a change that should fix it here: https://github.com/luxtorpeda-dev/packages/commit/9660297de58a1307e483b54886fa1a2a87e428d0

This will copy a raze-template.ini to raze.ini in the game directory if it does not exist. This seems to fix the issue with first launch on raze and blood.

Let me know if you all have issues.

**Closed by d10sfan** 2021-08-09 21:28 UTC
Labels: engine bug

**Comment by JoshuaFern** [comment] 2021-08-09 23:04
After trying raze again I got the same error as before, `Initialization: BLOOD.INI does not exist`, I then deleted my `~/.config/raze` directory and the game started working again. 
If I copy `raze.ini` from the game directory to `~/.config/raze/raze.ini` it seems to break again.

**Comment by d10sfan** [comment] 2021-08-09 23:31
It sounds like the existence of the one in the user coming means the local game directory one does not work? If so does it work if you remove the reference to the config in the command when the user config exists? If so that could be checked on. Seems strange it would look at the user config one when it's told to use a different one

**Comment by JoshuaFern** [comment] 2021-08-10 00:24
It's strange that it would prefer the default location when another location is present, and it's strange that one would cause an issue but the other doesn't even though they're the same exact configuration - or maybe it's a problem that they're both there at the same time. Either way the strange behavior of this engine continues to confuse me.

**Comment by d10sfan** [comment] 2021-08-10 02:47
Strange, I don't have an issue when I have both configurations (~/.config/raze.ini and the game directory raze.ini)

If you can replicate it, can you try removing these lines from the raze.ini in the game directory?

Path=$HOME/.config/raze
Path=$HOME/.config/raze/*

**Comment by JoshuaFern** [comment] 2021-08-10 02:57
> If you can replicate it, can you try removing these lines from the raze.ini in the game directory?
> 
> Path=$HOME/.config/raze
> Path=$HOME/.config/raze/*

No dice, same behavior with these lines removed.

**Comment by d10sfan** [comment] 2021-08-10 03:05
Weird, not sure why it doesn't happen for me. Does removing the -config raze.ini part of the command fix it when the ~/.config/raze exists? As in the game one still exists but we aren't setting it?

**Comment by JoshuaFern** [comment] 2021-08-10 03:40
I tried again without the `-config raze.ini` part of the command and it still didn't work. So I deleted the .config/raze folder again to let it autogenerate and it worked again.

The game directory config has `defaultiwad=` while .config/raze has `defaultiwad=BLOOD.RFF`, that's the only change I can see.

**Comment by d10sfan** [comment] 2021-08-10 04:05
@JoshuaFern Does that change make it work without any changes, as in making the game directory config have defaultiwad=BLOOD.RFF?

**Comment by McMarius11** [comment] 2021-08-10 16:27
i tried your new fixes and i still need those 2 files in my game folder
nblood.cfg
nblood.pk3
then it will work

**Comment by d10sfan** [comment] 2021-08-10 17:38
@McMarius11 I think I may have fixed the launch of cryptic when using nblood with this: https://github.com/luxtorpeda-dev/packages/commit/8c34e167de19c2c39951217230c2e707ff864d0e

Let me know if that fixes that.

**Comment by McMarius11** [comment] 2021-08-10 19:08
> @McMarius11 I think I may have fixed the launch of cryptic when using nblood with this: [8c34e16](https://github.com/luxtorpeda-dev/packages/commit/8c34e167de19c2c39951217230c2e707ff864d0e)
> 
> Let me know if that fixes that.

sorry for the trouble, i was so confused with the menu wallpaper, if i click on new game it will show the cryptic passage episode.
i was so irritated, with raze it looked different.
i tried your fix both work great!

**Comment by d10sfan** [comment] 2021-08-10 19:10
Great!

**Comment by JoshuaFern** [comment] 2021-08-11 04:02
> @JoshuaFern Does that change make it work without any changes, as in making the game directory config have defaultiwad=BLOOD.RFF?

No, I tried fiddling with that and it doesn't make a difference. For me right now I have to make sure `~/.config/raze/raze.ini` does not exist and the game will start and work fine for me. The moment I launch raze outside of Steam and that .config file regenerates Luxtorpeda will not work again.

**Comment by McMarius11** [comment] 2021-08-12 16:28
@JoshuaFern could you try to copy all files from Blood/lib/ into Blood folder and then open up a terminal and type in

./raze -iwad blood.rff
./raze -gamegrp blood.rff

and

./raze -iwad blood.rff -con cryptic.ini -file "addons/Cryptic Passage/"
./raze -gamegrp blood.rff -con cryptic.ini -file "addons/Cryptic Passage/"

and try if you get errors or if it runs without the choose iwad file error.

**Comment by JoshuaFern** [comment] 2021-08-12 20:42
It's working well enough for me right now, I'm going to give it a rest.
